version: "3.7"

services:
  react:
    image: wirebarley-test-front
    ports:
      - 3000:3000
    container_name: wirebarley_front
    networks:
      - network

  localhost:
    image: wirebarley-test-back
    ports:
      - "28080:28080"
    container_name: localhost
    restart: always
    networks:
      - network

networks:
  network: